### ISSUE TITLE
Add option to use LN-auth

### ISSUE THREAD

**Issue by Darth-Coin** [GaloyMoney/blink-mobile#3215] opened 2024-04-24 11:21 UTC
Please add the option to use Blink to login on sites with LN-auth
https://github.com/lnurl/luds/blob/luds/04.md

**Comment by nicolasburtey** [comment] 2024-05-23 17:59
duplicate of https://github.com/GaloyMoney/blink-mobile/issues/3137

**Closed by nicolasburtey** 2024-05-23 17:59 UTC
